# Generated by Django 4.1.3 on 2023-02-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=16, verbose_name='版本号')),
                ('publish_system', models.SmallIntegerField(choices=[(1, '案款系统'), (2, '涉众系统'), (1, '法银系统'), (2, '易案款')], default=1, verbose_name='发布系统')),
                ('publish_date', models.DateField(verbose_name='')),
                ('qxmd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='缺陷密度')),
                ('qxsl', models.IntegerField(verbose_name='缺陷数量')),
                ('ryqx', models.IntegerField(verbose_name='容易缺陷')),
                ('yzqx', models.IntegerField(verbose_name='严重缺陷')),
                ('ycxgbl', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='一次性关闭率')),
                ('is_xqps', models.SmallIntegerField(choices=[(1, '是'), (2, '否')], default=1, verbose_name='级别')),
                ('is_xqcd', models.SmallIntegerField(choices=[(1, '是'), (2, '否')], default=1, verbose_name='级别')),
                ('is_sjps', models.SmallIntegerField(choices=[(1, '是'), (2, '否')], default=1, verbose_name='级别')),
                ('is_csylps', models.SmallIntegerField(choices=[(1, '是'), (2, '否')], default=1, verbose_name='级别')),
                ('is_xnpg', models.SmallIntegerField(choices=[(1, '是'), (2, '否')], default=1, verbose_name='级别')),
                ('is_xqyz', models.SmallIntegerField(choices=[(1, '是'), (2, '否')], default=1, verbose_name='级别')),
                ('is_tcys', models.SmallIntegerField(choices=[(1, '是'), (2, '否')], default=1, verbose_name='级别')),
                ('is_cehjcs', models.SmallIntegerField(choices=[(1, '是'), (2, '否')], default=1, verbose_name='级别')),
                ('is_wdhjcs', models.SmallIntegerField(choices=[(1, '是'), (2, '否')], default=1, verbose_name='级别')),
            ],
        ),
    ]
