# Generated by Django 4.1 on 2023-02-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='publish_date',
            field=models.DateField(verbose_name='发布日期'),
        ),
    ]
