# Generated by Django 4.1 on 2023-02-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_data', '0003_rename_publish_system_testdata_c_publish_system_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdata',
            old_name='is_tcys',
            new_name='yis_tcys',
        ),
        migrations.RemoveField(
            model_name='testdata',
            name='c_publish_system',
        ),
        migrations.AddField(
            model_name='testdata',
            name='n_systemtype',
            field=models.SmallIntegerField(choices=[(1, '案款系统'), (2, '涉众系统'), (3, '法银系统'), (4, '易案款')], default=1, verbose_name='发布系统'),
        ),
    ]
