# Generated by Django 4.1 on 2023-02-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_data', '0005_orderdata_alter_testdata_is_cehjcs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdata',
            old_name='yis_tcys',
            new_name='is_tcys',
        ),
    ]
